<?php

use Illuminate\Database\Seeder;

class SeederTableDataCalon extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arr = array(
            array(
                "calon_id" => 1, 
                "kriteria_id" => 1, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 2, 
                "kriteria_id" => 1, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 3, 
                "kriteria_id" => 1, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 4, 
                "kriteria_id" => 1, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 5, 
                "kriteria_id" => 1, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 6, 
                "kriteria_id" => 1, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 7, 
                "kriteria_id" => 1, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 8, 
                "kriteria_id" => 1, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 9, 
                "kriteria_id" => 1, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 10, 
                "kriteria_id" => 1, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 11, 
                "kriteria_id" => 1, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 12, 
                "kriteria_id" => 1, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 13, 
                "kriteria_id" => 1, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 14, 
                "kriteria_id" => 1, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 15, 
                "kriteria_id" => 1, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 1, 
                "kriteria_id" => 2, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 2, 
                "kriteria_id" => 2, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 3, 
                "kriteria_id" => 2, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 4, 
                "kriteria_id" => 2, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 5, 
                "kriteria_id" => 2, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 6, 
                "kriteria_id" => 2, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 7, 
                "kriteria_id" => 2, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 8, 
                "kriteria_id" => 2, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 9, 
                "kriteria_id" => 2, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 10, 
                "kriteria_id" => 2, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 11, 
                "kriteria_id" => 2, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 12, 
                "kriteria_id" => 2, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 13, 
                "kriteria_id" => 2, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 14, 
                "kriteria_id" => 2, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 15, 
                "kriteria_id" => 2, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 1, 
                "kriteria_id" => 3, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 2, 
                "kriteria_id" => 3, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 3, 
                "kriteria_id" => 3, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 4, 
                "kriteria_id" => 3, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 5, 
                "kriteria_id" => 3, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 6, 
                "kriteria_id" => 3, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 7, 
                "kriteria_id" => 3, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 8, 
                "kriteria_id" => 3, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 9, 
                "kriteria_id" => 3, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 10, 
                "kriteria_id" => 3, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 11, 
                "kriteria_id" => 3, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 12, 
                "kriteria_id" => 3, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 13, 
                "kriteria_id" => 3, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 14, 
                "kriteria_id" => 3, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 15, 
                "kriteria_id" => 3, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 1, 
                "kriteria_id" => 4, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 2, 
                "kriteria_id" => 4, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 3, 
                "kriteria_id" => 4, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 4, 
                "kriteria_id" => 4, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 5, 
                "kriteria_id" => 4, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 6, 
                "kriteria_id" => 4, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 7, 
                "kriteria_id" => 4, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 8, 
                "kriteria_id" => 4, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 9, 
                "kriteria_id" => 4, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 10, 
                "kriteria_id" => 4, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 11, 
                "kriteria_id" => 4, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 12, 
                "kriteria_id" => 4, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 13, 
                "kriteria_id" => 4, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 14, 
                "kriteria_id" => 4, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 15, 
                "kriteria_id" => 4, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 1, 
                "kriteria_id" => 5, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 2, 
                "kriteria_id" => 5, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 3, 
                "kriteria_id" => 5, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 4, 
                "kriteria_id" => 5, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 5, 
                "kriteria_id" => 5, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 6, 
                "kriteria_id" => 5, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 7, 
                "kriteria_id" => 5, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 8, 
                "kriteria_id" => 5, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 9, 
                "kriteria_id" => 5, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 10, 
                "kriteria_id" => 5, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 11, 
                "kriteria_id" => 5, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 12, 
                "kriteria_id" => 5, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 13, 
                "kriteria_id" => 5, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 14, 
                "kriteria_id" => 5, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 15, 
                "kriteria_id" => 5, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 1, 
                "kriteria_id" => 6, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 2, 
                "kriteria_id" => 6, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 3, 
                "kriteria_id" => 6, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 4, 
                "kriteria_id" => 6, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 5, 
                "kriteria_id" => 6, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 6, 
                "kriteria_id" => 6, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 7, 
                "kriteria_id" => 6, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 8, 
                "kriteria_id" => 6, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 9, 
                "kriteria_id" => 6, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 10, 
                "kriteria_id" => 6, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 11, 
                "kriteria_id" => 6, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 12, 
                "kriteria_id" => 6, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 13, 
                "kriteria_id" => 6, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 14, 
                "kriteria_id" => 6, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 15, 
                "kriteria_id" => 6, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 1, 
                "kriteria_id" => 7, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 2, 
                "kriteria_id" => 7, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 3, 
                "kriteria_id" => 7, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 4, 
                "kriteria_id" => 7, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 5, 
                "kriteria_id" => 7, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 6, 
                "kriteria_id" => 7, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 7, 
                "kriteria_id" => 7, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 8, 
                "kriteria_id" => 7, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 9, 
                "kriteria_id" => 7, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 10, 
                "kriteria_id" => 7, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 11, 
                "kriteria_id" => 7, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 12, 
                "kriteria_id" => 7, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 13, 
                "kriteria_id" => 7, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 14, 
                "kriteria_id" => 7, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 15, 
                "kriteria_id" => 7, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 1, 
                "kriteria_id" => 8, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 2, 
                "kriteria_id" => 8, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 3, 
                "kriteria_id" => 8, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 4, 
                "kriteria_id" => 8, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 5, 
                "kriteria_id" => 8, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 6, 
                "kriteria_id" => 8, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 7, 
                "kriteria_id" => 8, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 8, 
                "kriteria_id" => 8, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 9, 
                "kriteria_id" => 8, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 10, 
                "kriteria_id" => 8, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 11, 
                "kriteria_id" => 8, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 12, 
                "kriteria_id" => 8, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 13, 
                "kriteria_id" => 8, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 14, 
                "kriteria_id" => 8, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 15, 
                "kriteria_id" => 8, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 1, 
                "kriteria_id" => 9, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 2, 
                "kriteria_id" => 9, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 3, 
                "kriteria_id" => 9, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 4, 
                "kriteria_id" => 9, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 5, 
                "kriteria_id" => 9, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 6, 
                "kriteria_id" => 9, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 7, 
                "kriteria_id" => 9, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 8, 
                "kriteria_id" => 9, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 9, 
                "kriteria_id" => 9, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 10, 
                "kriteria_id" => 9, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 11, 
                "kriteria_id" => 9, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 12, 
                "kriteria_id" => 9, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 13, 
                "kriteria_id" => 9, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 14, 
                "kriteria_id" => 9, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 15, 
                "kriteria_id" => 9, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 1, 
                "kriteria_id" => 10, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 2, 
                "kriteria_id" => 10, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 3, 
                "kriteria_id" => 10, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 4, 
                "kriteria_id" => 10, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 5, 
                "kriteria_id" => 10, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 6, 
                "kriteria_id" => 10, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 7, 
                "kriteria_id" => 10, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 8, 
                "kriteria_id" => 10, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 9, 
                "kriteria_id" => 10, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 10, 
                "kriteria_id" => 10, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 11, 
                "kriteria_id" => 10, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 12, 
                "kriteria_id" => 10, 
                "nilai" => 2, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 13, 
                "kriteria_id" => 10, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 14, 
                "kriteria_id" => 10, 
                "nilai" => 4, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "calon_id" => 15, 
                "kriteria_id" => 10, 
                "nilai" => 3, 
                "tahun_id" => 1, 
                "created_at" => "2017-08-27 23:11", 
                "updated_at" => "2017-08-27 23:11", 
                "created_by" => 1, 
                "updated_by" => 1)
        );

        DB::table("data_calon")->insert($arr);
    }
}
