<?php

use Illuminate\Database\Seeder;

class SeederTablePerbandinganKriteria extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arr = array(
            array(
                "kriteria_id_1" => 1, 
                "kriteria_id_2" => 2, 
                "tingkat_kepentingan_id" => 5, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 1, 
                "kriteria_id_2" => 3, 
                "tingkat_kepentingan_id" => 5, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 1, 
                "kriteria_id_2" => 4, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 1, 
                "kriteria_id_2" => 5, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 1, 
                "kriteria_id_2" => 6, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 1, 
                "kriteria_id_2" => 7, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 1, 
                "kriteria_id_2" => 8, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 1, 
                "kriteria_id_2" => 9, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 1, 
                "kriteria_id_2" => 10, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 2, 
                "kriteria_id_2" => 3, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 2, 
                "kriteria_id_2" => 4, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 2, 
                "kriteria_id_2" => 5, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 2, 
                "kriteria_id_2" => 6, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 2, 
                "kriteria_id_2" => 7, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 2, 
                "kriteria_id_2" => 8, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 2, 
                "kriteria_id_2" => 9, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 2, 
                "kriteria_id_2" => 10, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 3, 
                "kriteria_id_2" => 4, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 3, 
                "kriteria_id_2" => 5, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 3, 
                "kriteria_id_2" => 6, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 3, 
                "kriteria_id_2" => 7, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 3, 
                "kriteria_id_2" => 8, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 3, 
                "kriteria_id_2" => 9, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 3, 
                "kriteria_id_2" => 10, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 4, 
                "kriteria_id_2" => 5, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 4, 
                "kriteria_id_2" => 6, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 4, 
                "kriteria_id_2" => 7, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 4, 
                "kriteria_id_2" => 8, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 4, 
                "kriteria_id_2" => 9, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 4, 
                "kriteria_id_2" => 10, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 5, 
                "kriteria_id_2" => 6, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 5, 
                "kriteria_id_2" => 7, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 5, 
                "kriteria_id_2" => 8, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 5, 
                "kriteria_id_2" => 9, 
                "tingkat_kepentingan_id" => 3, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 5, 
                "kriteria_id_2" => 10, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 6, 
                "kriteria_id_2" => 7, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 6, 
                "kriteria_id_2" => 8, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 6, 
                "kriteria_id_2" => 9, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 6, 
                "kriteria_id_2" => 10, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 7, 
                "kriteria_id_2" => 8, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 7, 
                "kriteria_id_2" => 9, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 7, 
                "kriteria_id_2" => 10, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 8, 
                "kriteria_id_2" => 9, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 8, 
                "kriteria_id_2" => 10, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1), 
            array(
                "kriteria_id_1" => 9, 
                "kriteria_id_2" => 10, 
                "tingkat_kepentingan_id" => 1, 
                "created_at" => "2017-08-27 23:24", 
                "updated_at" => "2017-08-27 23:24", 
                "created_by" => 1, 
                "updated_by" => 1)
        );

        DB::table("perbandingan_kriteria")->insert($arr);
    }
}
